// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Jqa9u8PC62QE18eW9jT_36kar3BE1eE',
    appId: '1:280130064422:web:f88a9ea71e11b585c256e7',
    messagingSenderId: '280130064422',
    projectId: 'rnappz-34c16',
    authDomain: 'rnappz-34c16.firebaseapp.com',
    storageBucket: 'rnappz-34c16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUzX4EYLvHRXL2DPuF7aw3jwEgxHCTIM',
    appId: '1:280130064422:android:0d0368af0a178046c256e7',
    messagingSenderId: '280130064422',
    projectId: 'rnappz-34c16',
    storageBucket: 'rnappz-34c16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgE74VOFPoKWaQvwEzsgOlbJFNrCB5ZbY',
    appId: '1:280130064422:ios:1972b30102b8c593c256e7',
    messagingSenderId: '280130064422',
    projectId: 'rnappz-34c16',
    storageBucket: 'rnappz-34c16.appspot.com',
    iosClientId: '280130064422-aqmdoqslm3bcm1882gk77tjsprr27afd.apps.googleusercontent.com',
    iosBundleId: 'com.socialapp.blades.blades',
  );
}
